### ISSUE TITLE
[bug] SHIFT+numeric key shortcuts not working?

### ISSUE THREAD

**Issue by alvaromartmart** [ngneat/hotkeys#11]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Shortcuts such as shift+1 don't seem to work. 

## Expected behavior

shift + [numeric key] shortcuts should work.

## Minimal reproduction of the problem with instructions

I've put up an example on Stackblitz to illustrate the issue.
https://stackblitz.com/edit/ngneathotkeysdemo?embed=1&file=src/app/app.component.html

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
We are using the Angular mechanism under the hood, so you should check there.

**Comment by alvaromartmart** [comment]
Oh, I see... typing SHIFT+1 whould actually fire `keydown.shift.!` (or other, depending on the keyboard configuration).
It would be nice if I could refer to the value of `event.code` instead of `event.key` when defining the trigger, do you know if that's possible out of the box?

Anyway, I guess I can just close this as it's not really an issue with the library... thanks!

**Comment by NetanelBasal** [comment]
No, you can't.
