### ISSUE TITLE
Hotkey is being captured when user if focusing on input element

### ISSUE THREAD

**Issue by 24hours** [ngneat/hotkeys#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using trying to enter some key value into <input> element, the key value which coincide with hotkey will not appear and relavent  function is triggered. 

## Expected behavior
Hotkey should not trigger when using typing text.

## What is the motivation / use case for changing the behavior?
When using hotkeys in the environment where typing value is unavoidable, ie: enter search query. 

## Environment
Angular version: 9.1.0

Browser:
- [x] Chrome (desktop) version 83
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.8.1
- Platform:  Linux

**Comment by NetanelBasal** [comment]
@flatstadt we need to support it. Like we did [here](https://github.com/ngneat/hotkeys/blob/master/projects/ngneat/hotkeys/src/lib/hotkeys.service.ts#L117).

**Comment by NetanelBasal** [comment]
@24hours just to be sure. You register a hotkey on a different element, and when you type in a text input, it's get triggered, right?

**Comment by flatstadt** [comment]
> here

I'll look into it @NetanelBasal

**Comment by 24hours** [comment]
> @24hours just to be sure. You register a hotkey on a different element, and when you type in a text input, it's get triggered, right?

I registered the hotkey using hotkey service.

**Comment by flatstadt** [comment]
I replicated the issue @NetanelBasal. I created a div that contains an input. Associating a shortcut to the div, for example 'G', prevents typing 'g' in the input.

**Comment by NetanelBasal** [comment]
Do you know how to handle this?

**Comment by flatstadt** [comment]
Kind of. If you disable the preventDefault option, it works. But of course, by default an input element bubbles up all key events, and  preventDefault, well, prevents typing in the letter that matches the shortcut. I'm not sure if it's a bug.

**Comment by flatstadt** [comment]
I could use srcElement, to exclude inputs and textareas and ignore preventDefault option event when enable as an option.

**Comment by NetanelBasal** [comment]
@24hours what's exactly your use case? In which key you're using?

**Comment by NetanelBasal** [comment]
@flatstadt we can check event.target, and if that's an input/textarea we'll not run the callback. But there are cases where you want to register hotkeys for inputs so we need to support it too.

**Comment by flatstadt** [comment]
So, we ignore the callback when the target is an input/textarea, but the event was registered on another element.

**Comment by NetanelBasal** [comment]
Yes, but event.target will be the input.

**Comment by flatstadt** [comment]
> Yes, but event.target will be the input.

Yep. srcElement is deprecated @NetanelBasal

**Comment by NetanelBasal** [comment]
Implement the same functionality as here: https://github.com/chieffancypants/angular-hotkeys#api

The `allowIn` option.

**Comment by NetanelBasal** [comment]
https://github.com/chieffancypants/angular-hotkeys#allowing-hotkeys-in-form-elements

**Comment by 24hours** [comment]
> @24hours what's exactly your use case? In which key you're using? Please share the code.

My application allow user to interact with the image using WASD key, at the same time, there is a search bar which allow user to search for specific image. Users are not able to search image with character w,a,s,d in it. 

Since the hotkey is global, the event is binded to windows element. I guess this is why it got triggered in input element.

**Comment by NetanelBasal** [comment]
Fixed in the latest version.
