### ISSUE TITLE
Idea on allowing user to change hotkey. 

### ISSUE THREAD

**Issue by 24hours** [ngneat/hotkeys#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently when hotkey is defined by programmer, there is no way for user to override the choice of hotkey. 

## Expected behavior

User should be able to override hotkey configuration especially on key event. 

## What is the motivation / use case for changing the behavior?

While it is possible to add extra logic to unsubscribe certain hotkey and rebind it with different key, it would be great if user can change them on helpModal.

There is quite abit of code / ui to consider. Please close this if it does not align with the interest of this project. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
It's not related to the library. You need to save the hotkeys in the server, and register them on app load.

**Comment by 24hours** [comment]
> It's not related to the library. You need to save the hotkeys in the server, and register them on app load.

Storing hotkeys is not related to library, user may choose to store them on localstorage depending on their user case. 

However, 

I'm trying to say that.

1. currently there is no easy way to edit hotkey without resorting to edit source code / refreshing browser. 
2. user to have to create a series of logic to detect the hotkey which end-user desired to trigger a certain function. 
3. It would be helpful if hotkey editing UI is added to helpModal.

**Comment by NetanelBasal** [comment]
You can provide your own component, and do it. I don't think it's a common use case.
