### ISSUE TITLE
Upgrade dependencies to Angular 10

### ISSUE THREAD

**Issue by kaplan81** [ngneat/hotkeys#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe: Upgrade dependencies to Angular 10
</code></pre>

## Current behavior

When trying:

```ts
ng update @angular/core @angular/cli
```

We get:

```bash
Package "@ngneat/hotkeys" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.0.2").
Package "@ngneat/hotkeys" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would install "10.0.2").
```

## Expected behavior

No warnings.

## What is the motivation / use case for changing the behavior?

dependencies, devDependencies and peerDependencies should be aligned with the latest Angular version.

## Environment

<pre><code>
Angular CLI: 9.1.5
Node: 12.13.1
OS: darwin x64

Angular: 9.1.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.5
@angular-devkit/build-angular      0.901.5
@angular-devkit/build-ng-packagr   0.901.5
@angular-devkit/build-optimizer    0.901.5
@angular-devkit/build-webpack      0.901.5
@angular-devkit/core               9.1.5
@angular-devkit/schematics         9.1.5
@angular/cdk                       9.2.3
@angular/cli                       9.1.5
@angular/material                  9.2.3
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.5
@schematics/angular                9.1.5
@schematics/update                 0.901.5
ng-packagr                         9.1.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by NetanelBasal** [comment]
We need to update the peer deps

**Comment by kaplan81** [comment]
Keep me posted.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by hervehobbes** [comment]
Hello,

Sorry but it's not running for me, I still have this error message:

`
 ERROR in node_modules/@ngneat/hotkeys/lib/hotkeys.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@ngneat/hotkeys) which declares HotkeysModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    1 export declare class HotkeysModule {
                           ~~~~~~~~~~~~~
`

**Comment by solkaz** [comment]
@hervehobbes the version still needs to be bumped to reflect the changes I made (regarding peerDependencies), but I'm not sure if my changes would help your issue.

@NetanelBasal when would you be able to bump the package version?

**Comment by NetanelBasal** [comment]
@flatstadt can you release it, please?

**Comment by resamsel** [comment]
Any chance this gets released?

**Comment by NetanelBasal** [comment]
Done

**Comment by sinsunsan** [comment]
I still have same error as @hervehobbes  on a angular 10 site with IVY
 
 
 ```
 ERROR in node_modules/@ngneat/hotkeys/lib/hotkeys.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@ngneat/hotkeys) which declares HotkeysModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    1 export declare class HotkeysModule {
                           ~~~~~~~~~~~~~
                           
                          ```
