### ISSUE TITLE
How to define a hotkey which contains '.' key

### ISSUE THREAD

**Issue by jnewman30** [ngneat/hotkeys#18]
## How to define a hotkey which contains '.' key
*ngneat/hotkeys@1.1.1*

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

<pre><code>
hotkeys.addShortcut({keys: 'alt..'})  // how to specify hotkey of alt + .
</code></pre>

## Expected behavior

Hotkey Combo = alt + .

## Minimal reproduction of the problem with instructions

*Does nothing and can't seem to find a way to do it out of the box.*
<pre><code>
hotkeys.addShortcut({keys: 'alt..'});
</code></pre>

## What is the motivation / use case for changing the behavior?

Would be nice to include '.' character in hotkey combination.

## Environment

<pre><code>
Angular version: 9.1.7
Latest Version of Angular Untested.

Browser:
- [x] Chrome (desktop) version 84.0.4147.105
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 84.0.522.49
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Windows

Others:
N/A

**Comment by NetanelBasal** [comment]
Can you reproduce it on stackblitz, please?
