### ISSUE TITLE
Multi-language issues: check key code, instead of value

### ISSUE THREAD

**Issue by Iworb** [ngneat/hotkeys#24]
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you have multiple languages in your system, like I do, this module will work exaclty for language you're defined: `shift.meta.p` will work for English, but not for russian `shift.meta.з`, which has same key code, but different key value.

## Expected behavior

Add ability to check key code, not just key value.

## Minimal reproduction of the problem with instructions

* Add some localization to your system with letters, different than English;
* Create shortcut for English keys;
* Switch localization and try to use this hotkey.

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by Iworb** [comment]
No, its issue report

**Comment by rabiedadi** [comment]
I think using keycode instead of key value is better solution I had a problem when I add shortcuts for '(' and ')' to toggle panels
but they are not firing in mac devices because the key values of the same buttons are 0 and 9 in mac keyboard

**Comment by ItaiBarkav** [comment]
There is any update for this problem?

**Comment by TekVanDo** [comment]
I think this task can be closed. 

I took some time to get, but angular EventManager supports event.code sintax like `shift.code.KeyP` instead of `shift.p`
This will work regardless of the keyboard layout :

` this.hotkeys.addShortcut({
        keys: 'shift.code.KeyR',
      }).subscribe();`
