### ISSUE TITLE
@angular/material hard dep?

### ISSUE THREAD

**Issue by iCrawl** [ngneat/hotkeys#3]
Hey, as I was trying to just install this module and tried to use it, it seems it has a hard dep on `@angular/material`?

```
ERROR in The target entry-point "@ngneat/hotkeys" has missing dependencies:
 - @angular/material/dialog
```

https://github.com/ngneat/hotkeys/blob/354e9af48fb9e6dd9503240ac74af00c1002ab43/projects/ngneat/hotkeys/src/lib/hotkeys.module.ts#L12

I don't really see why this is necessary (at least in the library code), the example uses it but there's no reason to have this import in the library if that is the only case.

**Comment by NetanelBasal** [comment]
A legacy code. Do you want to create a PR and remove it?

**Comment by NetanelBasal** [comment]
Never mind, I'm on it.
