### ISSUE TITLE
contenteditable attribute is not handled.

### ISSUE THREAD

**Issue by LalitAgrawala004** [ngneat/hotkeys#36]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, By default, the library prevents hotkey callbacks from firing when their event originates from an input, select, or textarea element. It should also consider contenteditable attribute

## Expected behavior

- Hotkeys callback should not be triggered if event originates from contenteditable element.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to create a PR

**Comment by earcherc** [comment]
I'm solving this problem now. Will make a PR for feedback.

**Comment by marvin-belonio** [comment]
this doesn't work for me with angular 13.3.1 / hotkeys 1.2, but if i do the same check the service does in the subscribe function it returns true for the question of if its a contenteditable element.

my issues specifically rises with a prosemirror implementation (ngx-editor) but the element is correctly marked as contenteditable=true
