### ISSUE TITLE
Support sequential hot keys

### ISSUE THREAD

**Issue by jherman** [ngneat/hotkeys#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

Handle sequential hot keys like Gmail. For example you hit 'g' then 'i' and it goes to inbox. Something like '>' could be used as an indicator instead of '.', when splitting the string.

**Comment by NetanelBasal** [comment]
You're welcome to create a PR
