### ISSUE TITLE
Dependency free help modal?

### ISSUE THREAD

**Issue by andreaslarssen** [ngneat/hotkeys#82]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request?
[ ] Documentation issue or request?
[ ] Support request
[x] Other: Question to document or support
</code></pre>

## Current behavior

The documentation for the help modal relies on MatDialog dependency:
```
this.hotkeys.registerHelpModal(() => {
  const ref = this.dialog.open(HotkeysHelpComponent, { width: '500px' });
  ref.componentInstance.dismiss.subscribe(() => ref.close());
});
```

## Expected behavior

It would be nice if it was possible to have a help modal without the need to install extra dependencies

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gethari** [comment]
+1

**Comment by gethari** [comment]
> I ended up making my own package, mostly because of #81 but also wanting to solve it a bit different

Do you have a link for the package or fork ? and do you mind sharing what change you made different ?

**Comment by NetanelBasal** [comment]
Cool, so closing the issue.
