### ISSUE TITLE
Angular v16 Support

### ISSUE THREAD

**Issue by puranjayjain** [ngneat/hotkeys#83]
## I'm submitting a...
I want to help upgrade this library to support the latest version of angular.

## Current behavior
Docs mention proper support till 14

## Expected behavior
Should support 16 and beyond also.

## What is the motivation / use case for changing the behavior?
Support for the latest version of angular.

## Environment
Angular version: 16.2.0

For Tooling issues:
- Node version: v18.16.0
- Platform:   Mac

**Comment by gethari** [comment]
I have created a PR for it #84  , But I am waiting for maintainer inputs to remove or get rid of `@angular/material`

**Comment by puranjayjain** [comment]
thanks @gethari
