### ISSUE TITLE
Version 1.4.0 with Angular >=16 compatibility

### ISSUE THREAD

**Issue by 4gray** [ngneat/hotkeys#87]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Firstly thanks for the library. I have a small question regarding the releases. 
The [readme](https://github.com/ngneat/hotkeys#compatibility-with-angular-versions) mentions version 1.4.0 which is supposed to support Angular >=16 and which probably still uses `@angular/material`. Unfortunately I couldn't find it anywhere, is there a release planned for this or is it available somewhere and am I missing it?

**Comment by NetanelBasal** [comment]
It's a mistake, should v2 - https://github.com/ngneat/hotkeys/blob/master/CHANGELOG.md#-breaking-changes
